<?xml version="1.0" encoding="utf-8"?><Database Name="PaniDB" Class="DataBaseModelDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-6PRTJ4F\PROJECT;Initial Catalog=PaniDB;Integrated Security=True" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="PaniDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.PaniUser" Member="PaniUsers">
    <Type Name="PaniUser">
      <Column Name="User_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Administrator" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.EnlistUser" Method="EnlistUser">
    <ElementType Name="EnlistUserResult">
      <Column Name="Número" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Usuario" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Contraseña" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Administrador" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.UpdateUser" Method="UpdateUser">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="Username" Parameter="username" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Admin" Parameter="admin" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertUser" Method="InsertUser">
    <Parameter Name="Username" Parameter="username" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Admin" Parameter="admin" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteUser" Method="DeleteUser">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SearchUser" Method="SearchUser">
    <Parameter Name="search" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="SearchUserResult">
      <Column Name="Número" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Usuario" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Contraseña" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Administrador" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.EnlistSubmodalities" Method="EnlistSubmodalities">
    <ElementType Name="EnlistSubmodalitiesResult">
      <Column Name="[Número modalidad]" Member="Número_modalidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Sub-Modalidad]" Member="Sub_Modalidad" Type="System.String" DbType="VarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="Molidad" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.InsertSubmodality" Method="InsertSubmodality">
    <Parameter Name="submodality" Type="System.String" DbType="VarChar(300)" />
    <Parameter Name="modality" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>